### PR TITLE
frint-react: add `hydrate` function to `frint-react`

### LINKED ISSUE #335: frint-react: support hydration from server-rendered HTML
## Currently

We can only render in the browser targeting a specific node.

## Scenario for improvement

When HTML is rendered from the server, we don't really need to render everything again in the browser, since React can pick up from where the server rendering ended.

This can be achieved with `ReactDOM.hydrate`: https://reactjs.org/docs/react-dom.html#hydrate

Adding a new function in `frint-react` for `hydrate` would help achieve a nice solution for server-to-client flow.

### PR DESCRIPTION
**Pull request by rbardini**
## What's done

Add `hydrate` function to `frint-react`.

## Why

Support hydration from server-rendered HTML.

Closes #335.

### CODE REVIEW

**Comment by fahad19** [comment]
Great going, @rbardini! 💖

**Comment by fahad19** [comment]
please also update the README of `frint-react` 😬

**Comment by rbardini** [comment]
Totally forgot about it! Updated 🙂

**Comment by armand1m** [comment]
wow, nice! @rbardini great work!

**Pull request merged**
